version: "3"

services:
  sonarqube:
    image: sonarqube-branch
    build: .
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://<SONARQUBE-RDS-URL>.rds.amazonaws.com:5432/sonar?currentSchema=public
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=<VERY-STRONG-PASSWORD>
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_common:/opt/sonarqube/lib/common
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    restart: unless-stopped

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_common:

